"use strict";

const langs = {
	//Header
	"main":{
		eng: "Main",
		rus: "Главная",
		fra: "Principal",
		deu: "Hauptsächlich",
	},
	"about":{
		eng: "about",
		rus: "о нас",
		fra: "à propos",
		deu: "über uns",
	},
	"game":{
		eng: "game features",
		rus: "особенности игры",
		fra: "caractéristiques de jeu",
		deu: "Spielfunktionen",
	},
	"system":{
		eng: "System requirements",
		rus: "Системные Требования",
		fra: "Configuration requise",
		deu: "System Anforderungen",
	},
	"quotes":{
		eng: "quotes",
		rus: "цитаты",
		fra: "citations",
		deu: "Zitate",
	},
	//Main
	"main_title":{
		eng: "SURVIVE AT ALL COSTS",
		rus: "ВЫЖИТЬ ЛЮБОЙ ЦЕНОЙ",
		fra: "SURVIVRE À TOUT PRIX",
		deu: "ÜBERLEBEN SIE UM JEDEN KOSTEN",
	},
	"main_subtitle":{
		eng: "Experience new social battle royale game",
		rus: "Испытайте новую социальную игру в жанре королевской битвы",
		fra: "Découvrez le nouveau jeu social Battle Royale",
		deu: "Erlebe das neue soziale Battle-Royale-Spiel",
	},
	"main_text":{
		eng: "Buy now on Steam",
		rus: "Купить сейчас в Steam",
		fra: "Achetez maintenant sur Steam",
		deu: "Jetzt auf Steam kaufen",
	},
	"main_storytext":{
		eng: "The story",
		rus: "История",
		fra: "Histoire",
		deu: "Geschichte",
	},
	//About
	"about_title_what":{
		eng: "What is SOS?",
		rus: "Что такое SOS?",
		fra: "Qu’est-ce que le SOS?",
		deu: "Was ist SOS?",
	},
	"about_title_social":{
		eng: "social battle royale game",
		rus: "социальная королевская битва",
		fra: "bataille sociale royale",
		deu: "soziales Battle Royale",
	},
	"about_descr_p1":{
		eng: "Each round, <span>you</span> and <span>15</span> other contestants compete to escape a deadly island filled with monsters. The trick is: three people can survive. Will you run solo or form friendships with others to escape?",
		rus: "В каждом раунде <span>вы</span> и <span>15</span> других участников соревнуетесь, пытаясь выбраться со смертельного острова, наполненного монстрами. Хитрость в том, что три человека могут выжить. Будете ли вы бежать в одиночку или подружитесь с другими, чтобы сбежать?",
		fra: "À chaque tour, <span>vous</span> et <span>15</span> autres participants vous affrontez pour échapper à une île mortelle remplie de monstres. Le truc, c’est que trois personnes peuvent survivre. Allez-vous courir seul ou vous lier d’amitié avec d’autres pour vous échapper ?",
		deu: "In jeder Runde kämpfen <span>Sie</span> und <span>15</span> andere Teilnehmer darum, einer tödlichen Insel voller Monster zu entkommen. Der Trick besteht darin, dass drei Personen überleben können. Wirst du alleine laufen oder dich mit anderen anfreunden, um zu entkommen?",
	},
	"about_descr_p2":{
		eng: "Making the right decisions could be the difference between <span>life and death.</span>",
		rus: "Принятие правильных решений может стать решающим фактором между <span>жизнью и смертью.</span>",
		fra: "Prendre les bonnes décisions peut faire la différence entre <span>la vie et la mort.</span>",
		deu: "Die richtigen Entscheidungen zu treffen, kann über <span>Leben und Tod entscheiden.</span>",
	},
	//Features
	"features_title_what":{
		eng: "What’s so special?",
		rus: "Что такого особенного?",
		fra: "Qu'y a-t-il de si spécial ?",
		deu: "Was ist das Besondere?",
	},
	"features_title_features":{
		eng: "features",
		rus: "особенности",
		fra: "particularités",
		deu: "Besonderheiten",
	},
	"features_survive":{
		eng: "SURVIVE AT ALL COSTS",
		rus: "ВЫЖИТЬ ЛЮБОЙ ЦЕНОЙ",
		fra: "SURVIVRE À TOUT PRIX",
		deu: "ÜBERLEBEN SIE UM JEDEN KOSTEN",
	},
	"features_survive_text":{
		eng: "You have 30 minutes to find a relic, signal for extraction, and grab one of three spots on the rescue chopper.",
		rus: "У вас есть 30 минут, чтобы найти реликвию, подать сигнал об ее извлечении и занять одно из трех мест на спасательном вертолете.",
		fra: "Vous disposez de 30 minutes pour retrouver la relique, signaler sa récupération et prendre l'un des trois sièges de l'hélicoptère de sauvetage.",
		deu: "Sie haben 30 Minuten Zeit, um die Reliquie zu finden, ihre Bergung anzukündigen und einen der drei Plätze im Rettungshubschrauber einzunehmen.",
	},
	"features_create":{
		eng: "CREATE ALLIES AND ENEMIES",
		rus: "СОЗДАВАЙТЕ СОЮЗНИКОВ И ВРАГОВ",
		fra: "CRÉER DES ALLIÉS ET DES ENNEMIS",
		deu: "SCHAFFE VERBÜNDETE UND FEINDE",
	},
	"features_create_text":{
		eng: "You have 30 minutes to find a relic, signal for extraction, and grab one of three spots on the rescue chopper.",
		rus: "У вас есть 30 минут, чтобы найти реликвию, подать сигнал об ее извлечении и занять одно из трех мест на спасательном вертолете.",
		fra: "Vous disposez de 30 minutes pour retrouver la relique, signaler sa récupération et prendre l'un des trois sièges de l'hélicoptère de sauvetage.",
		deu: "Sie haben 30 Minuten Zeit, um die Reliquie zu finden, ihre Bergung anzukündigen und einen der drei Plätze im Rettungshubschrauber einzunehmen.",
	},
	"features_impress":{
		eng: "IMPRESS THE AUDIENCE",
		rus: "Впечатлите аудиторию",
		fra: "Impressionnez votre public",
		deu: "Beeindrucken Sie Ihr Publikum",
	},
	"features_impress_text":{
		eng: "You have 30 minutes to find a relic, signal for extraction, and grab one of three spots on the rescue chopper.",
		rus: "У вас есть 30 минут, чтобы найти реликвию, подать сигнал об ее извлечении и занять одно из трех мест на спасательном вертолете.",
		fra: "Vous disposez de 30 minutes pour retrouver la relique, signaler sa récupération et prendre l'un des trois sièges de l'hélicoptère de sauvetage.",
		deu: "Sie haben 30 Minuten Zeit, um die Reliquie zu finden, ihre Bergung anzukündigen und einen der drei Plätze im Rettungshubschrauber einzunehmen.",
	},
	//System
	"system_title_can":{
		eng: "Can My Computer Run this game?",
		rus: "Может ли мой компьютер запустить эту игру?",
		fra: "Mon ordinateur peut-il exécuter ce jeu ?",
		deu: "Kann mein Computer dieses Spiel ausführen?",
	},
	"system_title_system":{
		eng: "system requirements",
		rus: "СИСТЕМНЫЕ ТРЕБОВАНИЯ",
		fra: "CONFIGURATION REQUISE",
		deu: "SYSTEM ANFORDERUNGEN",
	},
	"system_table_os":{
		eng: "OS:",
		rus: "ос:",
		fra: "so:",
		deu: "os:",
	},
	"system_table_windows":{
		eng: "Windows 7 64-bit only (No OSX support at this time)",
		rus: "Только Windows 7 64-битная (В настоящее время нет поддержки OSX)",
		fra: "Windows 7 64 bits uniquement (actuellement pas de support OSX)",
		deu: "Nur Windows 7 64-Bit (derzeit keine OSX-Unterstützung)",
	},
	"system_table_processor":{
		eng: "pROCESSOR:",
		rus: "ПРОЦЕССОР:",
		fra: "CPU:",
		deu: "ZENTRALPROZESSOR:",
	},
	"system_table_intel":{
		eng: "Intel Core 2 Duo @ 2.4 GHZ or AMD Athlon X2 @ 2.8 GHZ",
		rus: "Intel Core 2 Duo @ 2,4 ГГц или AMD Athlon X2 @ 2,8 ГГц",
		fra: "Intel Core 2 Duo à 2,4 GHz ou AMD Athlon X2 à 2,8 GHz",
		deu: "Intel Core 2 Duo @ 2,4 GHz oder AMD Athlon X2 @ 2,8 GHz",
	},
	"system_table_memory":{
		eng: "mEMORY:",
		rus: "Память:",
		fra: "Mémoire:",
		deu: "Speicher:",
	},
	"system_table_gb":{
		eng: "8 GB RAM",
		rus: "8 ГБ оперативной памяти",
		fra: "8 Go de RAM",
		deu: "8 GB Arbeitsspeicher",
	},
	"system_table_storage":{
		eng: "storage:",
		rus: "хранилище:",
		fra: "stockage:",
		deu: "Lagerung:",
	},
	"system_table_space":{
		eng: "8 GB available space",
		rus: "8 ГБ свободного места",
		fra: "8 Go d'espace libre",
		deu: "8 GB freier Speicherplatz",
	},
	"system_table_graphics":{
		eng: "GRAPHICS:",
		rus: "ГРАФИКА:",
		fra: "le graphique:",
		deu: "GRAFIK:",
	},
	"system_table_nvidia":{
		eng: "NVIDIA GeForce GTX 660 2GB or  AMD Radeon HD 7850 2GB DirectX11 (Shader Model 5)",
		rus: "NVIDIA GeForce GTX 660 2 ГБ или AMD Radeon HD 7850 2 ГБ DirectX11 (шейдерная модель 5)",
		fra: "NVIDIA GeForce GTX 660 2 Go ou AMD Radeon HD 7850 2 Go DirectX11 (Shader Model 5)",
		deu: "NVIDIA GeForce GTX 660 2 GB oder AMD Radeon HD 7850 2 GB DirectX11 (Shader Model 5)",
	},
	//Quotes
		"quotes_what":{
		eng: "What people think?",
		rus: "Что думают люди?",
		fra: "Qu’en pensent les gens?",
		deu: "Was denken die Leute?",
	},
	"quotes_press":{
		eng: "Press quotes",
		rus: "Цитаты прессы",
		fra: "Citations de presse",
		deu: "Pressezitate",
	},
	"quotes_desc":{
		eng: "Our goal is to create a product and service that you’re satisfied with and use it every day. This is why we’re constantly working on our services to make it better every day and really listen to what our users has to say.",
		rus: "Наша цель — создать продукт и услугу, которыми вы будете довольны, и использовать их каждый день. Вот почему мы постоянно работаем над нашими сервисами, чтобы сделать их лучше каждый день, и действительно прислушиваемся к тому, что говорят наши пользователи.",
		fra: "Notre objectif est de créer un produit et un service dont vous êtes satisfait et que vous utilisez quotidiennement. C'est pourquoi nous travaillons constamment sur nos services pour les améliorer chaque jour et écouter réellement ce que nos utilisateurs ont à dire.",
		deu: "Unser Ziel ist es, ein Produkt und eine Dienstleistung zu schaffen, mit denen Sie zufrieden sind und die Sie jeden Tag nutzen. Aus diesem Grund arbeiten wir ständig an unseren Dienstleistungen, um sie jeden Tag besser zu machen und hören wirklich zu, was unsere Benutzer zu sagen haben.",
	},
	"quotes_btn":{
		eng: "<span>r</span>ead more testimonials",
		rus: "<span>ч</span>итать больше отзывов",
		fra: "<span>l</span>ire plus de témoignages",
		deu: "<span>l</span>esen Sie weitere Erfahrungsberichte",
	},
	"comment_1_name":{
		eng: "Evan Lahti",
		rus: "Эван Лахти",
		fra: "Evan Lahti",
		deu: "Evan Lahti",
	},
	"comment_1_prof":{
		eng: "PC Gamer",
		rus: "ПК-геймер",
		fra: "Joueur sur PC",
		deu: "PC-Spieler",
	},
	"comment_1_text":{
		eng: "“One of my gaming highlights of the year.”",
		rus: "“Один из моих игровых моментов года”.",
		fra: "“L'un de mes moments forts en matière de jeu de l'année.”",
		deu: "“Eines meiner Gaming-Highlights des Jahres.”",
	},
	"comment_1_date":{
		eng: "October 18, 2018",
		rus: "18 октября 2018 г.",
		fra: "18 octobre 2018",
		deu: "18. Oktober 2018",
	},
	"comment_2_name":{
		eng: "Jada Griffin",
		rus: "Джада Гриффин",
		fra: "Jada Griffin",
		deu: "Jada Griffin",
	},
	"comment_2_prof":{
		eng: "Nerdreactor",
		rus: "Ботаник Реактор",
		fra: "Nerdréacteur",
		deu: "Nerdreaktor",
	},
	"comment_2_text":{
		eng: "“The next big thing in the world of streaming and survival games.”",
		rus: "“Следующее большое событие в мире стриминговых игр и игр на выживание.”",
		fra: "“La prochaine grande nouveauté dans le monde du streaming et des jeux de survie.”",
		deu: "“Das nächste große Ding in der Welt der Streaming- und Survival-Spiele.”",
	},
	"comment_2_date":{
		eng: "December 21, 2018",
		rus: "21 декабря 2018 г.",
		fra: "21 décembre 2018",
		deu: "21. Dezember 2018",
	},
	"comment_3_name":{
		eng: "Aaron Williams",
		rus: "Аарон Уильямс",
		fra: "Aaron Williams",
		deu: "Aaron Williams",
	},
	"comment_3_prof":{
		eng: "Uproxx",
		rus: "Упрокс",
		fra: "Uproxx",
		deu: "Uproxx",
	},
	"comment_3_text":{
		eng: "“Snoop Dogg Playing The Wildly Entertaining ‘SOS’ Is Ridiculous.”",
		rus: "“Снуп Догг, играющий дико занимательную программу «SOS», просто смешон.”",
		fra: "“Snoop Dogg jouant le « SOS » extrêmement divertissant est ridicule.”",
		deu: "“Snoop Dogg, der das äußerst unterhaltsame „SOS“ spielt, ist lächerlich.”",
	},
	"comment_3_date":{
		eng: "December 24, 2018",
		rus: "24 декабря 2018 г.",
		fra: "24 décembre 2018",
		deu: "24. Dezember 2018",
	},
	//Newsletter
	"newsletter_want":{
		eng: "Want to stay in touch?",
		rus: "Хотите оставаться на связи?",
		fra: "Vous voulez rester connecté?",
		deu: "Möchten Sie in Verbindung bleiben?",
	},
	"newsletter_subscribe":{
		eng: "newsletter SUBSCRIBE",
		rus: "ПОДПИСАТЬСЯ на новостную рассылку",
		fra: "Abonnez-vous à la newsletter",
		deu: "Abonnieren Sie den Newsletter",
	},
	"newsletter_text":{
		eng: "In order to start receiving our news, all you have to do is enter your email address. Everything else will be taken care of by us. We will send you emails containing information about game. We don’t spam.",
		rus: "Чтобы начать получать наши новости, все, что вам нужно сделать, это ввести свой адрес электронной почты. Обо всем остальном позаботимся мы. Мы отправим вам электронные письма с информацией об игре. Мы не рассылаем спам.",
		fra: "Pour commencer à recevoir nos actualités, il vous suffit de saisir votre adresse email. Tout le reste sera pris en charge par nous. Nous vous enverrons des e-mails contenant des informations sur le jeu. Nous ne spammons pas.",
		deu: "Um unsere Neuigkeiten zu erhalten, müssen Sie lediglich Ihre E-Mail-Adresse eingeben. Alles Weitere wird von uns erledigt. Wir senden Ihnen E-Mails mit Informationen zum Spiel. Wir spammen nicht.",
	},
	"newsletter_adress":{
		eng: "Your email address",
		rus: "Ваш электронный адрес",
		fra: "Votre adresse e-mail",
		deu: "Ihre E-Mail-Adresse",
	},
	"newsletter_btn":{
		eng: "<span>S</span>ubscribe now",
		rus: "<span>П</span>одпишись сейчас",
		fra: "<span>a</span>bonnez-vous maintenant",
		deu: "<span>a</span>Abonniere jetzt",
	},
	"newsletter_rights":{
		eng: "© 2018 Outpost Games, Inc. All Rights Reserved",
		rus: "© Outpost Games, Inc., 2018. Все права защищены.",
		fra: "© 2018 Outpost Games, Inc. Tous droits réservés",
		deu: "© 2018 Outpost Games, Inc. Alle Rechte vorbehalten",
	},
	"newsletter_privacy":{
		eng: "Privacy Policy",
		rus: "политика конфиденциальности",
		fra: "politique de confidentialité",
		deu: "Datenschutzrichtlinie",
	},
	"newsletter_terms":{
		eng: "Terms of Services",
		rus: "Условия предоставления услуг",
		fra: "Conditions de services",
		deu: "Nutzungsbedingungen",
	},
	"newsletter_code":{
		eng: "Code of Conduct",
		rus: "Нормы поведения",
		fra: "Code de conduite",
		deu: "Verhaltenskodex",
	},
};
export default langs;